// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0aBRwdp8grGMXQx_YvbdhhYndjBHF0A',
    appId: '1:529066145890:web:f6a411cda109d9073ab93b',
    messagingSenderId: '529066145890',
    projectId: 'buildmaster-rev1',
    authDomain: 'buildmaster-rev1.firebaseapp.com',
    storageBucket: 'buildmaster-rev1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmtcoiLRuyUwCc7B_RxSb-IJwK0x5K9Y',
    appId: '1:529066145890:android:77ae5ffec71f0f5e3ab93b',
    messagingSenderId: '529066145890',
    projectId: 'buildmaster-rev1',
    storageBucket: 'buildmaster-rev1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsVNDeNH9dC4pQ-GpdhgRMM7_FilUCXM',
    appId: '1:529066145890:ios:c6022f94de95a23a3ab93b',
    messagingSenderId: '529066145890',
    projectId: 'buildmaster-rev1',
    storageBucket: 'buildmaster-rev1.appspot.com',
    iosClientId: '529066145890-j1kf52dmtc6mggv1qmlfio191h58i4p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildmasterRev2',
  );
}
